"""fix_fk_career_profile

Revision ID: 3e619ca3a7cd
Revises: 33e662c94f96
Create Date: 2024-06-01 10:43:55.650490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e619ca3a7cd'
down_revision: Union[str, None] = '33e662c94f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('responsibility_profile_fkey', 'responsibility', type_='foreignkey')
    op.create_foreign_key(None, 'responsibility', 'career_profile', ['profile'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responsibility', type_='foreignkey')
    op.create_foreign_key('responsibility_profile_fkey', 'responsibility', 'competence_profile', ['profile'], ['id'])
    # ### end Alembic commands ###
