"""add_user

Revision ID: 90ede10325c1
Revises: a57b0e652f26
Create Date: 2024-06-01 08:59:18.180242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ede10325c1'
down_revision: Union[str, None] = 'a57b0e652f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('cv', sa.Column('user', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'cv', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cv', type_='foreignkey')
    op.drop_column('cv', 'user')
    op.drop_table('user')
    # ### end Alembic commands ###
