"""add_the_level_to_the_language

Revision ID: fbeb4ba91c8d
Revises: 90ede10325c1
Create Date: 2024-06-01 09:48:49.706222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbeb4ba91c8d'
down_revision: Union[str, None] = '90ede10325c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('level', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language', 'level')
    # ### end Alembic commands ###
